### ISSUE TITLE
Payment Made Order Status ID should come from ini

### ISSUE THREAD

**Issue by brookinsconsulting** [mugoweb/ezpaypal#1]
https://github.com/mugoweb/ezpaypal/blob/699df96da5e36f359ad07e94c7cc9813ed037426/classes/ezpaypalchecker.php#L179

Hello mugo,

I find the static assessment of order status 1000 to be a bit restrictive and would prefer a paypal.ini setting instead. 

What do you say to a PR to add the setting?

Cheers,
Brookins Consulting

**Comment by brookinsconsulting** [comment]
Hello,

I created a pull request with the desired changes waiting for your review, https://github.com/mugoweb/ezpaypal/pull/3

Cheers,
Brookins Consulting

**Comment by pkamps** [comment]
Related pull request got merged.
