### ISSUE TITLE
Documentation should state this is a redirect nvp api

### ISSUE THREAD

**Issue by brookinsconsulting** [mugoweb/ezpaypal#2]
https://github.com/mugoweb/ezpaypal/blob/699df96da5e36f359ad07e94c7cc9813ed037426/README#L6

Hello mugo,

When implementing ezpaypal for a small coffee shop among others I find the lack of docs even mentions that this is a redirect gateway for the ezp admin workflow system. When testing we lacked what exact api by PayPal was implemented to ensure this solution was still supported by PayPal service 

Here above would be a great place to include these notes clearly explaining.

What do you think. Ps this tool works well to this very day for new shops.

Cheers,
Brookins Consulting

**Comment by brookinsconsulting** [comment]
Hello,

I added a new PR, https://github.com/mugoweb/ezpaypal/pull/4 to address some of the missing key info needed to get it working.

Please accept these changes. they are small.

Cheers,
Brookins Consulting

**Comment by pkamps** [comment]
Related pull request got merged.
